# Generated by Django 5.1.15 on 2026-09-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_sitesettings_order_notification_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="announcement_messages",
            field=models.TextField(
                blank=True,
                help_text="One message per line, shown in the bar at the top of the storefront. Leave blank to hide the bar.",
                verbose_name="Announcement bar messages",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="brands_enabled",
            field=models.BooleanField(default=False, verbose_name="Brands"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="delivery_integration_enabled",
            field=models.BooleanField(
                default=True,
                help_text="ON: courier (Delhivery) shipments, tracking and webhooks work as usual. OFF: all courier UI is hidden and shipment status is updated manually from the dashboard.",
                verbose_name="Delivery Integration",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="gift_builder_enabled",
            field=models.BooleanField(default=False, verbose_name="Gift builder"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="newsletter_enabled",
            field=models.BooleanField(default=True, verbose_name="Newsletter"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="rentals_enabled",
            field=models.BooleanField(default=False, verbose_name="Rentals"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="subscriptions_enabled",
            field=models.BooleanField(default=False, verbose_name="Subscriptions"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(default="SIRI COUTURE", max_length=120),
        ),
    ]
