# Generated by Django 5.1.15 on 2026-09-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_rename_site_to_siri_couture"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="site_tagline",
            field=models.CharField(
                blank=True,
                help_text="Short line shown under the logo in the header (e.g. the brand strapline). Leave blank to hide.",
                max_length=80,
                verbose_name="Tagline",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="announcement_messages",
            field=models.TextField(
                blank=True,
                help_text="One message per line, shown in the bar at the top of the storefront. Optionally start a line with an icon name and a colon, e.g. 'truck: Your text'. Icons: truck, shield, globe, star, headset, return, card, gift, heart, leaf, weave. Leave blank to hide the bar.",
                verbose_name="Announcement bar messages",
            ),
        ),
    ]
