# Generated by Django 5.1.15 on 2026-09-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_siri_taglines"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="store_address",
            field=models.TextField(
                blank=True,
                help_text="Physical store address shown in the footer, contact page, and about page.",
                verbose_name="Store address",
            ),
        ),
    ]
