# Generated by Django 5.1.15 on 2026-09-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_sitesettings_store_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="bestseller_label",
            field=models.CharField(
                default="Bestseller",
                help_text="Display text for bestseller products — badge, filter, homepage section, and nav all use this.",
                max_length=40,
                verbose_name="Bestseller label",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="featured_label",
            field=models.CharField(
                default="Featured",
                help_text="Display text for featured products — badge, filter, homepage section, and nav all use this.",
                max_length=40,
                verbose_name="Featured label",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="new_arrival_label",
            field=models.CharField(
                default="New Arrivals",
                help_text="Display text for new arrival products — badge, filter, homepage section, and nav all use this.",
                max_length=40,
                verbose_name="New arrivals label",
            ),
        ),
    ]
