# Generated by Django 5.1.15 on 2026-09-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0012_alter_homepagesection_section_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="heroslide",
            name="cta_label",
            field=models.CharField(
                blank=True,
                help_text="Optional call-to-action button text. The button shows only when label and link are both set.",
                max_length=60,
                verbose_name="Button label",
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="cta_url",
            field=models.CharField(
                blank=True,
                help_text="Optional call-to-action URL or path (e.g. /shop/).",
                max_length=300,
                verbose_name="Button link",
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="eyebrow",
            field=models.CharField(
                blank=True,
                help_text="Optional small line shown above the title.",
                max_length=120,
                verbose_name="Eyebrow",
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="subtitle",
            field=models.CharField(
                blank=True,
                help_text="Optional line shown below the title.",
                max_length=200,
                verbose_name="Subtitle",
            ),
        ),
    ]
