# Generated by Django 5.1.15 on 2026-09-19 21:32

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0013_heroslide_editorial_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroslide",
            name="cta_url",
            field=models.CharField(
                blank=True,
                help_text="Optional call-to-action URL or path (e.g. /shop/).",
                max_length=300,
                validators=[cms.models.validate_link_target],
                verbose_name="Button link",
            ),
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("hero_slider", "Hero Slider"),
                    ("shop_by_category", "Shop by Category"),
                    ("featured_products", "Featured Products"),
                    ("new_arrivals", "New Arrivals"),
                    ("best_sellers", "Best Sellers"),
                    ("featured_brands", "Featured Brands"),
                    ("subscription_banner", "Subscription Banner"),
                    ("marketing_features", "Marketing Feature Cards"),
                    ("reviews", "Reviews"),
                    ("instagram_gallery", "Instagram Gallery"),
                    ("newsletter", "Newsletter"),
                    ("category_products", "Category Product Grids"),
                    ("promo_banners", "Promo Banners"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="Section type",
            ),
        ),
        migrations.CreateModel(
            name="PromoBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True,
                        help_text="Optional small line shown above the title.",
                        max_length=120,
                        verbose_name="Eyebrow",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Main heading. Also used as the image alt text.",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Optional line shown below the title.",
                        max_length=200,
                        verbose_name="Subtitle",
                    ),
                ),
                (
                    "cta_label",
                    models.CharField(
                        blank=True,
                        help_text="The button shows only when label and link are both set.",
                        max_length=60,
                        verbose_name="Button label",
                    ),
                ),
                (
                    "cta_url",
                    models.CharField(
                        blank=True,
                        help_text="Site path (e.g. /shop/) or full http(s) URL.",
                        max_length=300,
                        validators=[cms.models.validate_link_target],
                        verbose_name="Button link",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Background photo, ideally about 1200x600 (2:1). Without a photo the tile shows a solid maroon panel.",
                        upload_to="cms/promo/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Display order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Promo banner",
                "verbose_name_plural": "Promo banners",
                "ordering": ["display_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="cms_promo_active_order_idx"
                    )
                ],
            },
        ),
    ]
