# Generated by Django 5.1.15 on 2026-09-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0014_promobanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="promobanner",
            name="style",
            field=models.CharField(
                choices=[("tile", "Tile (two per row)"), ("wide", "Wide closing banner")],
                db_index=True,
                default="tile",
                help_text="Tile: shown two per row in the Promo Banners section. Wide: the first active one fills the Wide Banner section.",
                max_length=10,
                verbose_name="Style",
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Photo slide, landscape about 2.56:1 (recommended 2400x940; 2:1 to 2.8:1 accepted, at least 1000px wide). Ignored when a video is uploaded. All slides should share one size.",
                upload_to="cms/hero/images/",
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("hero_slider", "Hero Slider"),
                    ("shop_by_category", "Shop by Category"),
                    ("featured_products", "Featured Products"),
                    ("new_arrivals", "New Arrivals"),
                    ("best_sellers", "Best Sellers"),
                    ("featured_brands", "Featured Brands"),
                    ("subscription_banner", "Subscription Banner"),
                    ("marketing_features", "Marketing Feature Cards"),
                    ("reviews", "Reviews"),
                    ("instagram_gallery", "Instagram Gallery"),
                    ("newsletter", "Newsletter"),
                    ("category_products", "Category Product Grids"),
                    ("promo_banners", "Promo Banners"),
                    ("category_cards", "Category Cards"),
                    ("service_strip", "Service Strip"),
                    ("wide_banner", "Wide Banner"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="Section type",
            ),
        ),
        migrations.AlterField(
            model_name="promobanner",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Background photo. Tile: about 1200x600 (2:1). Wide: about 2400x480 (5:1). Without a photo a solid maroon panel is shown.",
                upload_to="cms/promo/",
                verbose_name="Photo",
            ),
        ),
        migrations.CreateModel(
            name="ServiceHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("truck", "Truck"),
                            ("shield", "Shield"),
                            ("globe", "Globe"),
                            ("star", "Star"),
                            ("headset", "Headset"),
                            ("return", "Return"),
                            ("card", "Card"),
                            ("gift", "Gift"),
                            ("heart", "Heart"),
                            ("leaf", "Leaf"),
                            ("weave", "Weave"),
                        ],
                        default="star",
                        max_length=20,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Short text; it wraps onto two lines (e.g. two words per line).",
                        max_length=80,
                        verbose_name="Label",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Display order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Service highlight",
                "verbose_name_plural": "Service highlights",
                "ordering": ["display_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="cms_service_active_order_idx"
                    )
                ],
            },
        ),
    ]
