# Generated by Django 5.1.15 on 2026-09-20 07:01

import cms.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0015_siri_home_sections"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Heading shown above the video.",
                        max_length=150,
                        verbose_name="Section title",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Optional line shown under the heading.",
                        max_length=200,
                        verbose_name="Subtitle",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        help_text="mp4 or webm, up to 100 MB. mp4 (H.264) plays everywhere.",
                        upload_to="cms/video/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp4", "webm", "ogg", "mov"]
                            ),
                            cms.models.validate_video_size,
                        ],
                        verbose_name="Video",
                    ),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        help_text="Still image shown before the video plays (recommended).",
                        upload_to="cms/video/posters/",
                        verbose_name="Cover image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Home video",
                "verbose_name_plural": "Home videos",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("hero_slider", "Hero Slider"),
                    ("shop_by_category", "Shop by Category"),
                    ("featured_products", "Featured Products"),
                    ("new_arrivals", "New Arrivals"),
                    ("best_sellers", "Best Sellers"),
                    ("featured_brands", "Featured Brands"),
                    ("subscription_banner", "Subscription Banner"),
                    ("marketing_features", "Marketing Feature Cards"),
                    ("reviews", "Reviews"),
                    ("instagram_gallery", "Instagram Gallery"),
                    ("newsletter", "Newsletter"),
                    ("category_products", "Category Product Grids"),
                    ("promo_banners", "Promo Banners"),
                    ("service_strip", "Service Strip"),
                    ("wide_banner", "Wide Banner"),
                    ("testimonials", "Testimonials"),
                    ("video_section", "Video"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="Section type",
            ),
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Customer name")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Optional, shown under the name (e.g. a city).",
                        max_length=100,
                        verbose_name="Location / description",
                    ),
                ),
                (
                    "quote",
                    models.TextField(
                        help_text="The customer's words (up to 400 characters).",
                        max_length=400,
                        verbose_name="Testimonial",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Square photo works best (at least 200x200). Without one, the customer's initial is shown.",
                        upload_to="cms/testimonials/",
                        verbose_name="Profile photo",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional, 1 to 5. Stars are hidden when blank.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Star rating",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Display order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["display_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="cms_testimonial_active_idx"
                    )
                ],
            },
        ),
    ]
