# Generated by Django 5.1.15 on 2026-09-20 07:55

import cms.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0016_homevideo_alter_homepagesection_section_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroslide",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Video slide (mp4 H.264 or webm), silent and looping. Keep it short and under about 15 MB for fast loading; the frame is about 2.5:1 on desktop, so keep the subject centred. Takes priority over the photo.",
                upload_to="cms/hero/videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(["mp4", "webm", "ogg", "mov"]),
                    cms.models.validate_video_size,
                ],
                verbose_name="Video",
            ),
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("hero_slider", "Hero Slider"),
                    ("shop_by_category", "Shop by Category"),
                    ("featured_products", "Featured Products"),
                    ("new_arrivals", "New Arrivals"),
                    ("best_sellers", "Best Sellers"),
                    ("featured_brands", "Featured Brands"),
                    ("subscription_banner", "Subscription Banner"),
                    ("marketing_features", "Marketing Feature Cards"),
                    ("reviews", "Reviews"),
                    ("instagram_gallery", "Instagram Gallery"),
                    ("newsletter", "Newsletter"),
                    ("category_products", "Category Product Grids"),
                    ("promo_banners", "Promo Banners"),
                    ("service_strip", "Service Strip"),
                    ("wide_banner", "Wide Banner"),
                    ("testimonials", "Testimonials"),
                    ("video_section", "Video"),
                    ("memories", "Memories Gallery"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="Section type",
            ),
        ),
        migrations.CreateModel(
            name="MemoryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Portrait photo works best (about 4:5, at least 600px wide). Resize very large photos before uploading.",
                        upload_to="cms/memories/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Optional short text shown over the photo (e.g. a name).",
                        max_length=100,
                        verbose_name="Caption",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Display order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Memory photo",
                "verbose_name_plural": "Memory photos",
                "ordering": ["display_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="cms_memory_active_order_idx"
                    )
                ],
            },
        ),
    ]
