# Generated by Django 5.1.15 on 2026-09-20 08:19

import cms.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0017_alter_heroslide_video_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homevideo",
            name="video",
            field=models.FileField(
                help_text="mp4 or webm, up to 100 MB. mp4 (H.264) plays everywhere. It plays automatically, silent and looping, with no controls.",
                upload_to="cms/video/",
                validators=[
                    django.core.validators.FileExtensionValidator(["mp4", "webm", "ogg", "mov"]),
                    cms.models.validate_video_size,
                ],
                verbose_name="Video",
            ),
        ),
    ]
