# Generated by Django 5.1.15 on 2026-09-25 13:07

from django.db import migrations


def rename_category_sections(apps, schema_editor):
    HomepageSection = apps.get_model("cms", "HomepageSection")
    Category = apps.get_model("catalog", "Category")
    Collection = apps.get_model("catalog", "Collection")

    category_slug_to_collection_slug = {
        category.slug: category.slug for category in Category.objects.all()
    }

    for section in HomepageSection.objects.filter(section_type="shop_by_category"):
        section.section_type = "shop_by_collection"
        section.save(update_fields=["section_type"])

    for section in HomepageSection.objects.filter(section_type="category_products"):
        config = dict(section.config or {})
        if "category_slug" in config:
            slug_val = config.pop("category_slug")
            if isinstance(slug_val, str) and slug_val != "all":
                slug_val = category_slug_to_collection_slug.get(slug_val, slug_val)
            config["collection_slug"] = slug_val
        section.config = config
        section.section_type = "collection_products"
        section.save(update_fields=["section_type", "config"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0018_homevideo_autoplay_help"),
        ("catalog", "0032_copy_category_to_collection_data"),
    ]

    operations = [
        migrations.RunPython(rename_category_sections, noop_reverse),
    ]
