# Generated by Django 5.1.15 on 2026-09-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0019_rename_category_sections_to_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagesection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("hero_slider", "Hero Slider"),
                    ("shop_by_collection", "Shop by Collection"),
                    ("featured_products", "Featured Products"),
                    ("new_arrivals", "New Arrivals"),
                    ("best_sellers", "Best Sellers"),
                    ("featured_brands", "Featured Brands"),
                    ("subscription_banner", "Subscription Banner"),
                    ("marketing_features", "Marketing Feature Cards"),
                    ("reviews", "Reviews"),
                    ("instagram_gallery", "Instagram Gallery"),
                    ("newsletter", "Newsletter"),
                    ("collection_products", "Collection Product Grids"),
                    ("promo_banners", "Promo Banners"),
                    ("service_strip", "Service Strip"),
                    ("wide_banner", "Wide Banner"),
                    ("testimonials", "Testimonials"),
                    ("video_section", "Video"),
                    ("memories", "Memories Gallery"),
                    ("product_spotlight", "Product Spotlight"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="Section type",
            ),
        ),
    ]
