# Generated by Django 5.1.15 on 2026-09-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0031_add_collections_and_facets"),
        ("marketing", "0004_delete_giftcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="applicable_collections",
            field=models.ManyToManyField(
                blank=True,
                related_name="coupons",
                to="catalog.collection",
                verbose_name="Applicable collections",
            ),
        ),
    ]
