# Generated by Django 5.1.15 on 2026-09-25 13:01

from django.db import migrations


def copy_applicable_categories(apps, schema_editor):
    Coupon = apps.get_model("marketing", "Coupon")
    Category = apps.get_model("catalog", "Category")
    Collection = apps.get_model("catalog", "Collection")

    category_slug_to_collection_id = dict(
        Collection.objects.values_list("slug", "id")
    )
    category_id_to_collection_id = {
        category.pk: category_slug_to_collection_id.get(category.slug)
        for category in Category.objects.all()
    }

    for coupon in Coupon.objects.prefetch_related("applicable_categories").all():
        category_ids = list(coupon.applicable_categories.values_list("id", flat=True))
        if not category_ids:
            continue
        collection_ids = [
            category_id_to_collection_id[cid]
            for cid in category_ids
            if category_id_to_collection_id.get(cid) is not None
        ]
        if collection_ids:
            coupon.applicable_collections.add(*collection_ids)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0005_add_collections_and_facets"),
        ("catalog", "0032_copy_category_to_collection_data"),
    ]

    operations = [
        migrations.RunPython(copy_applicable_categories, noop_reverse),
    ]
