# Generated by Django 5.1.15 on 2026-09-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0006_copy_applicable_categories_to_collections_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="applicable_categories",
        ),
    ]
