# Generated by Django 5.1.15 on 2026-09-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0025_productvariant_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="tagline",
            field=models.CharField(
                blank=True,
                help_text="Optional short italic line shown under the category name on homepage category cards.",
                max_length=80,
                verbose_name="Tagline",
            ),
        ),
    ]
