# Generated by Django 5.1.15 on 2026-09-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0026_siri_taglines"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="tagline",
            field=models.CharField(
                blank=True,
                help_text="Optional short italic line shown under the category title on its listing page.",
                max_length=80,
                verbose_name="Tagline",
            ),
        ),
    ]
