# Generated by Django 5.1.15 on 2026-09-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0027_category_tagline_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="show_on_homepage",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="When on, this category's products appear in the homepage category-rails section.",
                verbose_name="Show on homepage",
            ),
        ),
    ]
