# Generated by Django 5.1.15 on 2026-09-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0028_category_show_on_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="product",
            name="show_home_spotlight",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="When on, this product gets its own full PDP-style section on the homepage (drag-reorderable from Homepage Sections in the dashboard).",
                verbose_name="Show as homepage spotlight",
            ),
        ),
    ]
