# Generated by Django 5.1.15 on 2026-09-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0029_product_description_product_show_home_spotlight"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="care_instructions",
            field=models.TextField(blank=True, verbose_name="Care Instructions"),
        ),
    ]
