# Generated by Django 5.1.15 on 2026-09-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0030_product_care_instructions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the collection.",
                        max_length=120,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly collection identifier.",
                        max_length=120,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Optional short italic line shown under the collection title on its listing page.",
                        max_length=80,
                        verbose_name="Tagline",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(blank=True, max_length=70, verbose_name="Meta title"),
                ),
                (
                    "meta_description",
                    models.CharField(blank=True, max_length=160, verbose_name="Meta description"),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seo/collections/",
                        verbose_name="Open Graph image",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower values appear first in navigation.",
                        verbose_name="Display order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="When False, collection is hidden from the storefront.",
                        verbose_name="Is active",
                    ),
                ),
                (
                    "show_on_homepage",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="When on, this collection's products appear in the homepage collection-rails section.",
                        verbose_name="Show on homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(fields=["is_active"], name="cat_collection_is_active_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="collections",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="catalog.collection",
                verbose_name="Collections",
            ),
        ),
        migrations.CreateModel(
            name="Fabric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("slug", models.SlugField(max_length=120, unique=True, verbose_name="Slug")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="Display order"),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Fabric",
                "verbose_name_plural": "Fabrics",
                "ordering": ["display_order", "name"],
                "indexes": [models.Index(fields=["is_active"], name="cat_fabric_is_active_idx")],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="fabrics",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="catalog.fabric", verbose_name="Fabrics"
            ),
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("slug", models.SlugField(max_length=120, unique=True, verbose_name="Slug")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="Display order"),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
                "ordering": ["display_order", "name"],
                "indexes": [models.Index(fields=["is_active"], name="cat_grade_is_active_idx")],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="grades",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="catalog.grade", verbose_name="Grades"
            ),
        ),
        migrations.CreateModel(
            name="Occasion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("slug", models.SlugField(max_length=120, unique=True, verbose_name="Slug")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="Display order"),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Occasion",
                "verbose_name_plural": "Occasions",
                "ordering": ["display_order", "name"],
                "indexes": [models.Index(fields=["is_active"], name="cat_occasion_is_active_idx")],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="occasions",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="catalog.occasion", verbose_name="Occasions"
            ),
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("slug", models.SlugField(max_length=120, unique=True, verbose_name="Slug")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="Display order"),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Style",
                "verbose_name_plural": "Styles",
                "ordering": ["display_order", "name"],
                "indexes": [models.Index(fields=["is_active"], name="cat_style_is_active_idx")],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="styles",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="catalog.style", verbose_name="Styles"
            ),
        ),
    ]
