# Generated by Django 5.1.15 on 2026-09-25 13:01

from django.db import migrations


def copy_categories_to_collections(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    Collection = apps.get_model("catalog", "Collection")
    Product = apps.get_model("catalog", "Product")

    category_to_collection = {}
    for category in Category.objects.all():
        collection = Collection.objects.create(
            name=category.name,
            slug=category.slug,
            tagline=category.tagline,
            meta_title=category.meta_title,
            meta_description=category.meta_description,
            og_image=category.og_image,
            display_order=category.display_order,
            is_active=category.is_active,
            show_on_homepage=category.show_on_homepage,
        )
        category_to_collection[category.pk] = collection.pk

    for product in Product.objects.exclude(category__isnull=True):
        collection_id = category_to_collection.get(product.category_id)
        if collection_id is not None:
            product.collections.add(collection_id)


def noop_reverse(apps, schema_editor):
    """Not reversible: the destructive migration ahead of this one already
    drops Product.category/Category, so there is nothing to reconstruct."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0031_add_collections_and_facets"),
    ]

    operations = [
        migrations.RunPython(copy_categories_to_collections, noop_reverse),
    ]
