# Generated by Django 5.1.15 on 2026-09-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0032_copy_category_to_collection_data"),
        ("marketing", "0007_drop_category"),
        ("cms", "0019_rename_category_sections_to_collection"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="cat_prod_active_category_idx",
        ),
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
